esphome:
  name: $name
  name_add_mac_suffix: true
  platform: ESP8266
  board: nodemcuv2
  esp8266_restore_from_flash: true
  project:
    name: $project_name
    version: $project_version
  compile_process_limit: "1"

substitutions:
  status_led_inverted: "true"