esphome:
  name: $name
  name_add_mac_suffix: true
  compile_process_limit: "1"
  project:
    name: $project_name
    version: $project_version
  platformio_options:
    board_build.flash_mode: dio

esp32:  
  board: esp32-s3-devkitc-1
  framework:
    type: arduino
    version: recommended

substitutions:
  status_led_inverted: "false"
