esphome:
  name: $name
  name_add_mac_suffix: true
  compile_process_limit: "1"
  project:
    name: $project_name
    version: $project_version

esp32:  
  board: wesp32
  framework:
    type: arduino
    version: recommended

substitutions:
  status_led_inverted: "false"